bifrost:
  services:
    - service:
        name: bifrost.services.core.configuration_service.Configuration
        disabled: False
        watchdog_timer_s: 1
        topics:
          request_config_value:
            - 'Reconfiguration_Service.Request'
          utc_timestamp_now:
            - 'Bifrost.Configuration.UTC_Now'
          request_downlink_path:
            - 'Bifrost.Configuration.Downlink_Path'
        stream_declarations:
          Telemetry:
            - 'Telemetry.AOS.Raw.Beef'
            - 'Telemetry.AOS.Raw'

            - 'Telemetry.AOS.VCID.0.TaggedFrame'
            - 'Telemetry.AOS.VCID.Unknown.TaggedFrame'

            - 'Telemetry.AOS.VCID.0.TaggedPacket'

        key_values:
          global:
            mission:
              pass_id: ${PASS_ID}
            paths:
              data_path: ${DATA_PATH}
            aws:
              profile: ${AWS_PROFILE}
              bucket: ${AWS_S3_BUCKET}
              region: ${AWS_REGION}

          instance:
            space_vehicle:
              sv_name: ${SV_NAME}
              sv_identifier: ${SV_IDENTIFIER}
              ccsds_dl_scid: ${CCSDS_DOWNLINK_SCID}

    - service:
        name: bifrost.services.testing.examples.echo.Echo
        disabled: True
        topics:
          echo_alice:
            - Hello.Alice
          echo_bob:
            - Hello.Bob
          echo_mr_x:
            - Hello.Mr_x

    - service: 
        name: bifrost.services.testing.examples.echo.Hello
        disabled: True
        mr_x: Fujiko Mine
        #mr_x: Lupin The Third
        sleep: 10
  
    - service:
        name: bifrost.services.dsn_services.raf_downlink_service.SLE_RAF_Service
        disabled: ${SERVICE_SLE_RAF_DISABLE}
        report_time_s: ${SERVICE_SLE_RAF_REPORT_TIME_S}
        autorestart: ${SERVICE_SLE_RAF_AUTORESTART}
        output_stream: 'Telemetry.AOS.Raw'
        topics:
          directive_stop_sle:
            - 'Bifrost.Directive.SLE.RAF.Stop'
          directive_restart_sle:
            - 'Bifrost.Directive.SLE.RAF.Restart'
        
    - service:
        name: bifrost.services.dsn_services.cltu_uplink_service.SLE_CLTU_Uplink_Service
        disabled: ${SERVICE_SLE_CLTU_DISABLE}
        report_time_s: ${SERVICE_SLE_CLTU_REPORT_TIME_S}
        autorestart: ${SERVICE_SLE_CLTU_AUTORESTART}
        topics:
          directive_stop_sle:
            - 'Bifrost.Directive.SLE.CLTU.Stop'
          directive_restart_sle:
            - 'Bifrost.Directive.SLE.CLTU.Restart'
          uplink:
            - 'Uplink.CmdMetaData.CLTU'
        streams:
          Null

    - service:
        name: bifrost.services.core.web.Web_Server
        disabled: ${SERVICE_WEB_DISABLE}
        telemetry_stream_pattern: 'Telemetry.AOS.VCID.0.TaggedPacket.>'
        index: ${SERVICE_WEB_ROOT_DIRECTORY}
        downlink_update_pattern: 'Bifrost.Messages.Info.File_Processor.Downlink_Update'
        
    - service:
        name: bifrost.services.core.influx.Influx
        disabled: ${SERVICE_INFLUX_DISABLE}
        host_url: ${SERVICE_INFLUX_URL}
        api_token: '${SERVICE_INFLUX_TOKEN}'
        org: ${SERVICE_INFLUX_ORG}
        streams: Null
        topics:
          write_telemetry:
            - 'Telemetry.AOS.VCID.0.TaggedPacket.>'
          write_command_metadata:
            - Uplink.CmdMetaData.Log

    - service:
        name: bifrost.services.uplink.packet_padder.Packet_Padder
        disabled: ${SERVICE_PACKET_PADDER_DISABLE}
        topics:
          process:
            - Uplink.CmdMetaData.Space_Packet

    - service:
        name: bifrost.services.core.space_packet_service.Space_Packet_Service
        disabled: ${SERVICE_SPACE_PACKET_DISABLE}
        topics:
          packetize_cmd_metadata:
            - Uplink.CmdMetaData
          packetize_raw:
            - Bifrost.Services.Space_Packet.Packetize            
          depacketize:
            - Bifrost.Services.Space_Packet.Depacketize

    - service:
        name: bifrost.services.core.monitoring.Monitor
        disabled: ${SERVICE_MONITOR_DISABLE}
        topics:
          process:
            - 'Bifrost.Monitors.>'
        report_time_s: ${SERVICE_MONITOR_REPORT_TIME_S}

    - service:
        name: bifrost.services.uplink.tctf_service.TCTF_Service
        disabled: ${SERVICE_TCTF_DISABLE}
        topics:
          process:
            #- Uplink.CmdMetaData.Padded
            #- Uplink.CmdMetaData.Space_Packet
            - Uplink.CmdMetaData.FSS_Command
            - Uplink.CmdMetaData
    - service:
        name: bifrost.services.sdls_services.sdls_encrypter_service.SDLS_Encrypter_Service
        disabled: ${SERVICE_SDLS_ENCRYPTER_DISABLE}
        report_time_s: ${SERVICE_SDLS_ENCRYPTER_REPORT_TIME_S}
        topics:
          process:
            - Uplink.CmdMetaData.TCTF

    - service:
        name: bifrost.services.uplink.ccsds_randomizer_service.CCSDS_Randomizer_Service
        disabled: ${SERVICE_CCSDS_RANDOMIZER_DISABLE}
        topics:
          randomize_sdls:
            - Uplink.CmdMetaData.SDLS
          # randomize_tctf:
          # - Uplink.CmdMetaData.TCTF

    - service:
        name: bifrost.services.uplink.CLTU_service.CLTU_Service
        disabled: ${SERVICE_CLTU_DISABLE}
        CLTU_start: '0x55555555555555555555EB90'
        CLTU_tail: '0xc5c5c5c5c5c5c579'
        topics:
          process:
            #- Uplink.CmdMetaData.SDLS.Random
            #- Uplink.CmdMetaData.TCTF.Random
            #- Uplink.CmdMetaData.TCTF
            - Uplink.CmdMetaData.TCTF.BCH


    - service:
        name: bifrost.services.uplink.BCH_service.BCH_Service
        disabled: ${SERVICE_BCH_DISABLE}
        topics:
          encode_cmd_metadata:
            - Uplink.CmdMetaData.TCTF
            #- Uplink.CmdMetaData.SDLS.Random
            #- Uplink.CmdMetaData.TCTF.Random
          #encode:
          #  - ''

    - service:
        name: bifrost.services.extra.synchronization_service.Synchronization_Service
        disabled: ${SERVICE_SYNCHRONIZATION_DISABLE}
        topics:
          process:
            - create_CLTU

    - service:
        name: bifrost.services.networking.tcp_service.TCP_Manager
        disabled: ${SERVICE_TCP_DISABLE}
        report_time_s: ${SERVICE_TCP_REPORT_TIME_S}
        topics:
          process:            
            - Uplink.CmdMetaData.CLTU
          directive_config:
            - Bifrost.Directive.TCP_Manager.Config
          directive_disconnect:
            - Bifrost.Directive.TCP_Manager.Disconnect
          directive_connect:
            - Bifrost.Directive.TCP_Manager.Connect
          directive_reconnect:
            - Bifrost.Directive.TCP_Manager.Reconnect
            
        subscriptions:
          CMD_FSW_SIM:
            topic: Uplink.CmdMetaData.CLTU
            hostname: ${SERVICE_TCP_CMD_HOST}
            port: ${SERVICE_TCP_CMD_PORT}
            mode: TRANSMIT
            timeout_seconds: 1

          TLM_FSW_SIM:
            topic: Telemetry.AOS.Raw.Beef
            hostname: ${SERVICE_TCP_TLM_HOST}
            port: ${SERVICE_TCP_TLM_PORT}
            mode: RECEIVE
            timeout_seconds: 1

    - service:
        name: bifrost.services.downlink.frame_processors.real_time_processor.RealTime_Telemetry_Frame_Processor
        disabled: ${FRAME_PROCESSOR_REALTIME_DISABLE}
        topics: Null
        streams:
          process:
            - Telemetry.AOS.VCID.0.TaggedFrame

    - service:
        name: bifrost.services.extra.synchronization_service.Desynchronization_Service
        disabled: ${SERVICE_DESYNCHRONIZATION_DISABLE}
        topics: Null
        streams:
          desynchronize:
            - Telemetry.AOS.Raw.Beef

    - service:
        name: bifrost.services.extra.synchronization_service.ASM_Desynchronization_Service
        disabled: ${ASM_DESYNCHRONIZATION_SERVICE_DISABLE}
        topics: Null
        streams:
          desynchronize:
            - Telemetry.AOS.Raw.Beef # Change to ASM

    - service:
        name: bifrost.services.testing.data_loss_services.Loss_Service
        disabled: ${SERVICE_LOSS_DISABLE}
        active: ${SERVICE_LOSS_ACTIVE}
        percent: ${SERVICE_LOSS_PERCENT}
        announce: ${SERVICE_LOSS_ANNOUNCE}
        topics: Null
        streams:
          process:
            - Telemetry.AOS.Raw.Beef

    - service:
        name: bifrost.services.testing.data_loss_services.Corruption_Service
        disabled: ${SERVICE_CORRUPTION_DISABLE}
        active: ${SERVICE_CORRUPTION_ACTIVE}
        percent: ${SERVICE_CORRUPTION_PERCENT}
        announce: ${SERVICE_CORRUPTION_ANNOUNCE}
        topics: Null
        stream:
          process:
            - Telemetry.AOS.Raw.Beef
           
    - service:
        name: bifrost.services.downlink.frame_checks_service.AOS_Frame_Checks_Service
        disabled: ${SERVICE_AOS_FRAME_CHECKS_DISABLE}
        topics: Null
        fec_check: False
        streams:
          process:
            - Telemetry.AOS.Raw

    - service:
        name: bifrost.services.core.commanding.command_loader_service.Command_Loader_Service
        disabled: ${SERVICE_COMMAND_LOADER_DISABLE}
        default_cl_path: ${SERVICE_COMMAND_LOADER_DEFAULT_CL_PATH}
        default_uplink_path: ${SERVICE_COMMAND_LOADER_DEFAULT_UPLINK_PATH}
        topics:
          show:
            - CL.Show
          execute:
            - CL.Execute
          validate:
            - CL.Validate
          uplink_complete:
            - Uplink.CmdMetaData.Complete           

    - service:
        name: bifrost.services.core.dictionary_services.Command_Dictionary_Service
        disabled: ${SERVICE_COMMAND_DICTIONARY_DISABLE}
        topics:
          generate_command: 
            - 'Bifrost.Services.Dictionary.Command.Generate'
            - 'Bifrost.Services.Dictionary.Command.Validate'
          get_dictionary_json:
            - 'Bifrost.Services.Dictionary.Command.Json'

    - service:
        name: bifrost.services.downlink.frame_processors.frame_archive_processor.Frame_Archive_Processor
        disabled: ${TELEMETRY_PROCESSOR_FRAME_ARCHIVE_DISABLE}
        frame_ext: ${TELEMETRY_PROCESSOR_FRAME_ARCHIVE_EXTENSION}
        vcid_interests:
          0: True
        topics: Null
        streams:
          process:
            - 'Telemetry.AOS.VCID.*.TaggedFrame'

    - service:
        name: bifrost.services.testing.injector_service.Data_Injection_Service
        disabled: ${SERVICE_DATA_INJECTION_DISABLE}
        topics:
          inject_binary_stream:
            - 'Bifrost.Directive.Data_Injection_Service.Inject_Binary_Stream'

    - service:
        name: bifrost.services.testing.archive_services.Raw_Frame_Archive_Service
        disabled: ${SERVICE_RAW_FRAME_ARCHIVE_DISABLE}
        frame_extension: ${SERVICE_RAW_FRAME_ARCHIVE_EXTENSION}
        vcid_interests:
          0: True
        streams:
          archive:
            - 'Telemetry.AOS.Raw'

    - service:
        name: bifrost.services.extra.nasa_fss_service.NASA_FSS_Service
        disabled: ${SERVICE_NASA_FSS_DISABLE}
        topics:
          directive_command:
            - Bifrost.Directive.NASA_FSS_Service.Command

    - service:
        name: bifrost.services.downlink.evr_services.EVR_Service
        disabled: ${SERVICE_EVR_DISABLE}
        topics:
          process_evr:
            - "Telemetry.AOS.VCID.0.TaggedPacket.CFE_EVS_EVENT_MSG_PACKET"

    - service:
        name: bifrost.services.core.task_manager.task_manager.Task_Manager
        disabled: ${SERVICE_TASK_MANAGER_DISABLE}
        auto_s3_upload: ${SERVICE_TASK_MANAGER_AUTO_S3_UPLOAD}
        streams: Null
        topics:
          finalize_s3:
            - S3_File_Upload
          finalize:
            - Untar
            - Bz2_Decompress
            - CSV_to_Influx
          finalize_reassembly:
            - File_Reassembly

        task_transformers:
          # Taskname:
          #   Task Transformer 1:
          #   Task Transformer 2:
          #     filename_filters:
          #       - <Regular Expression>' # Single Quotes
          #     args:
          #        variable1: value
          #        variable2: value
          File_Reassembly:
            S3_File_Upload:
              filename_filters:
                - '.*'

            Untar:
              filename_filters:
                - '^sensors.*\.(tar)$'

          Untar:
            Bz2_Decompress:
              filename_filters:
                - '^sensors.*\.(bz2)$'

          Bz2_Decompress:
            Post_Process:
              filename_filters:
                - '^sensors.*[^.]{9}$' # Stop matching to avoid .metadata 
              args:
                processor:
                  - sensors
